name: 'Trigger Buildkite Pipeline'
author: 'Buildkite'
description: 'A GitHub Action for triggering a build on a Buildkite pipeline.'
inputs:
   buildkite-token:
     description: 'Buildkite API Access Token'
     required: true
   pipeline:
     description: 'The pipline to create a build on, in the format <org-slug>/<pipeline-slug>'
     required: true
   commit:
     description: 'The commit SHA of the build'
     required: false
   branch:
     description: 'The branch of the build'
     required: false
   message:
     description: 'The message for the build'
     required: false
   build-env-vars:
     description: 'Additional environment variables to set on the build, in JSON format'
     required: false
   build-meta-data:
     description: 'Meta-data to set on the build, in JSON format'
     required: false
   ignore-pipeline-branch-filter:
     description: 'Ignore pipeline branch filtering when creating a new build. true or false'
     required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
      BUILDKITE_API_ACCESS_TOKEN: ${{ inputs.buildkite-token }}    
      BUILD_ENV_VARS: ${{ inputs.build-env-vars }}      
      BUILD_META_DATA: ${{ inputs.build-meta-data }}      
      IGNORE_PIPELINE_BRANCH_FILTER: ${{ inputs.ignore-pipeline-branch-filter }}      