name: Trigger Buildkite Pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Trigger a Buildkite Build using GHA arguments'
        uses: "buildkite/trigger-pipeline-action@feature/support-action-inputs"
        with:
          buildkite_token: '1234567890' 
          pipeline:  'my-org/my-deploy-pipeline' 
          branch: 'master'
          commit: 'HEAD'
          message: ':github: Triggered from a GitHub Action'
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build_meta_data: '{"FOO": "bar"}'
          ignore_pipeline_branch_filter: true          