name: Unit Test

on: push

jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      steps:
  
        - name: Check out code
          uses: actions/checkout@v3 

        - name: Verify that the Docker image for the action builds
          run: docker build . --file Dockerfile         
     
    tests:
      name: unit-test
      runs-on: ubuntu-latest
      steps:
        - name: Run unit test for the action
          run: docker run --rm -i "./":/plugin buildkite/plugin-tester:v4.0.0
