name: Unit Test

on: push

jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      steps:
  
        - name: Check out code
          uses: actions/checkout@v3 

        - name: Verify that the Docker image for the action builds
          run: docker build . --file Dockerfile          
   