name: "Unit-test"
on: push

jobs:
    test: # make sure the action works on a clean machine without building 
        name: unit-test
        runs-on: ubuntu-latest
        steps:

        - name: Check out code
          uses: actions/checkout@v3

        - name: Verify that the Docker image for the action builds
          run: docker build . --file Dockerfile            

        - name: Setup BATS
          uses: mig4/setup-bats@v1
          with:
            bats-version: 1.2.1
        
        - name: Setup bats-lib
          run: source ./install-bats-lib.sh

        - name: BATS test
          run: bats tests/entrypoint.bats