name: Verify

on:
  push:
    branches: [ 'develop', 'main', 'master' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ 'develop', 'main', 'master' ]

jobs:
  tests:
    name: Integration tests112349
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile

#      - name: Run action with minimal parameters
#        uses: "buildkite/trigger-pipeline-action@v2.0.0"
#        with:
#          buildkite_api_access_token:  "bkua_f1ffa3a085faed2012888b2f7c1939af567f5845"
#          pipeline: "justTest-111/trigger-gitaction"
#          message: Triggered from GHA using minimal parameters
#          branch: master
#          commit: HEAD

      - name: Run action with all parameters
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        id: tests
        with:
          buildkite_api_access_token:  "bkua_f1ffa3a085faed2012888b2f7c1939af567f5845"
          pipeline: "justTest-111/trigger-gitaction"
          branch: master
          commit: HEAD
          message:  ":buildkite::github: 🚀🚀🚀 Triggered from GHA using commit message: ${{ github.event.head_commit.message }}"
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build_meta_data: '{"FOO": "bar"}'
          ignore_pipeline_branch_filter: true

      - name: Verify output
        run: echo ${{join(steps.tests.outputs.*, '\n')}}
