name: Verify

on: push

jobs:
  tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile

      - name: Run action with minimal parameters
        uses: ./
        with:
          buildkite_api_access_token:  "bkua_885b7a4c722aba19ffa298c4ec54d42b25fa287b"
          pipeline: "justTest-111/trigger-gitaction"
          message: Triggered from GHA using minimal parameters
          branch: master
          commit: HEAD

      - name: Run action with all parameters
        uses: ./
        id: tests
        with:
          buildkite_api_access_token:  "bkua_885b7a4c722aba19ffa298c4ec54d42b25fa287b"
          pipeline: "justTest-111/trigger-gitaction"
          branch: master
          commit: HEAD
          message:  ":buildkite::github: 🚀🚀🚀 Triggered from GHA using commit message: ${{ github.event.head_commit.message }}"
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build_meta_data: '{"FOO": "bar"}'
          ignore_pipeline_branch_filter: true

      - name: Verify output
        run: echo ${{join(steps.tests.outputs.*, '\n')}}
