name: Verify

on: push
 
jobs: 
  tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile      
 
      - name: Run action with required parameters
        uses: ./
        with:
          buildkite_api_access_token:  ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }} 
          pipeline: "lzrinc/experimental-pipeline"    
    