name: Verify

on:
  push:
    branches: [ 'develop', 'main', 'master' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ 'develop', 'main', 'master' ]

jobs:
  tests:
    name: Integration tests112322
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile
      - name: Trigger a Buildkite Build
          uses: "buildkite/trigger-pipeline-action@v2.0.0"
          with:
            buildkite_api_access_token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
            pipeline: "my-org/my-deploy-pipeline"
            branch: "master"
            commit: "HEAD"
            message:  ":github: Triggered from a GitHub Action"
            build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
            build_meta_data: '{"FOO": "bar"}'
            ignore_pipeline_branch_filter: true
#      - name: Run action with minimal parameters
#        uses: "buildkite/trigger-pipeline-action@v2.0.0"
#        with:
#          buildkite_api_access_token:  ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
#          pipeline: "justTest-111/trigger-gitaction"
#          message: Triggered from GHA using minimal parameters
#          branch: master
#          commit: HEAD


      - name: Verify output
        run: echo ${{join(steps.tests.outputs.*, '\n')}}
